export {default as CoverPage} from './CoverPage'
export {default as CTAPage} from './CTAPage'
export {default as InputFormPage} from './InputFormPage'
export {default as NotFoundPage} from './NotFoundPage'
export {default as HomePage} from './HomePage'